# Generated by Django 2.0.2 on 2018-02-23 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylink',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='mylink',
            name='tags',
        ),
        migrations.AddField(
            model_name='mylink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
