# Generated by Django 2.0.1 on 2018-01-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='catgory',
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='exams.Category'),
            preserve_default=False,
        ),
    ]
